Tweak the word2vec model to use two different corpora for training the word2vec model and disambiguate the analyses

diff --git a/w2v-weightlist b/w2v-weightlist
--- a/w2v-weightlist
+++ b/w2v-weightlist
@@ -3,6 +3,7 @@
 usage="$(basename "$0"): generate a disambiguated weightlist using a word2vec model
 USAGE: $(basename "$0") [-h] corpus input_file output_weightlist
 corpus	a raw corpus file
+corpus_w2v  a large raw corpus file for training the word2vec model
 input_file	the input compiled dictionary (a finite state transducer)
 output_weightlist	a weightlist for unambiguous words in corpus
 default_weightlist	a laplace smoothed weightlist for OOV words
@@ -32,15 +33,22 @@ while :; do
 done
 
 CORPUS=$1
-INPUT_FST=$2
-OUTPUT_WEIGHTLIST=$3
-DEFAULT_WEIGHTLIST=$4
+CORPUS_W2V=$2
+INPUT_FST=$3
+OUTPUT_WEIGHTLIST=$4
+DEFAULT_WEIGHTLIST=$5
 
 no_of_missing_args=0
 if [ ! -f "$CORPUS" ]
 then
 	printf "ERROR: corpus file \"%s\" doesn't exist\n" "$CORPUS" >&2
 	no_of_missing_args=$((no_of_missing_args + 1))
+fi
+
+if [ ! -f "$CORPUS_W2V" ]
+then
+    printf "ERROR: corpus file \"%s\" doesn't exist\n" "$CORPUS_W2V" >&2
+    no_of_missing_args=$((no_of_missing_args + 1))
 fi
 
 if [ ! -f "$INPUT_FST" ]
@@ -70,7 +78,7 @@ fi
 TEMP_DIR=$(mktemp -d)
 WORD_FILE="$TEMP_DIR/word"
 SIMILAR_WORD_FILE="$TEMP_DIR/similar"
-./utils/w2v_get_similar_words.py --corpus "$CORPUS" --output_words_file "$WORD_FILE" --output_similar_words_file "$SIMILAR_WORD_FILE"
+./utils/w2v_get_similar_words.py --corpus "$CORPUS" --corpus_w2v "$CORPUS_W2V" --output_words_file "$WORD_FILE" --output_similar_words_file "$SIMILAR_WORD_FILE"
 
 ANALYZED_WORDS="$TEMP_DIR/analyzed_words"
 ANALYZED_SIMILAR_WORDS="$TEMP_DIR/analyzed_similar_words"
@@ -82,4 +90,4 @@ apertium-destxt "$SIMILAR_WORD_FILE" | lt-proc "$INPUT_FST" | apertium-retxt > "
 CLEANED_WORDS="$TEMP_DIR/cleaned_words"
 apertium-cleanstream -n < "$ANALYZED_WORDS" > "$CLEANED_WORDS"
 
-./utils/w2v_generate_weights.py "$CLEANED_WORDS" "$ANALYZED_SIMILAR_WORDS" "$OUTPUT_WEIGHTLIST" "$DEFAULT_WEIGHTLIST"
+./utils/w2v_generate_weights.py --words_file "$CLEANED_WORDS" --similar_file "$ANALYZED_SIMILAR_WORDS" --output_weightlist "$OUTPUT_WEIGHTLIST" --default_weightlist "$DEFAULT_WEIGHTLIST"
